name       : haskell-gitrev
version    : 1.3.1
release    : 2
source     :
    - https://hackage.haskell.org/package/gitrev-1.3.1/gitrev-1.3.1.tar.gz : a89964db24f56727b0e7b10c98fe7c116d721d8c46f52d6e77088669aaa38332
license    : BSD-3-Clause
component  : programming.haskell
summary    : Some handy Template Haskell splices for including the current git hash and branch in the code of your project.
description: |
    Some handy Template Haskell splices for including the current git hash and branch in the code of your project.
builddeps  :
    - haskell-base-compat
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
